create table if not exists public.email_auth_requests (
  id bigint generated by default as identity primary key,
  email text not null,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists email_auth_requests_email_created_at_idx
  on public.email_auth_requests (email, created_at desc);

alter table public.email_auth_requests enable row level security;
